apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{ if eq .Values.storage.storageClassName "efs" }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: 1Gi
