apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: {{ include "web-server-role-name" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "web-server-role-binding-name" . }}
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "webserver-sa" . }}
roleRef:
  kind: Role
  name: {{ include "web-server-role-name" . }}
  apiGroup: rbac.authorization.k8s.io
