# MySQL base image
FROM mysql:latest

# Create Directory 
RUN mkdir -p /data/db

# Environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
